apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sentinel-proxy
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy
    spec:
      containers:
      - name: redis-sentinel-proxy
        image: patrickdk/redis-sentinel-proxy:v1.2
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MASTER
            value: primary
          - name: SENTINEL
            value: "redis-sentinel.$(NAMESPACE):26379"
        ports:
        - containerPort: 9999
        readinessProbe:
          exec:
            command: ["/health"]
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 9999
          periodSeconds: 10
          timeoutSeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
